"""empty message

Revision ID: 196bed34be59
Revises: da0396bad96e
Create Date: 2025-01-29 19:38:14.884089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196bed34be59'
down_revision = 'da0396bad96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=20), nullable=False))
        batch_op.drop_constraint('user_contrasena_key', type_='unique')
        batch_op.drop_constraint('user_nombre_key', type_='unique')
        batch_op.create_unique_constraint(None, ['password'])
        batch_op.drop_column('contrasena')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contrasena', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_nombre_key', ['nombre'])
        batch_op.create_unique_constraint('user_contrasena_key', ['contrasena'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###
