"""empty message

Revision ID: 440f34af2d1a
Revises: 6e7c6cfc2f9d
Create Date: 2025-01-31 12:41:02.525097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440f34af2d1a'
down_revision = '6e7c6cfc2f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_especie_key', type_='unique')
        batch_op.drop_constraint('people_nombre_key', type_='unique')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_nombre_key', type_='unique')
        batch_op.drop_constraint('planets_sistema_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_constraint('user_name_key', type_='unique')
        batch_op.drop_constraint('user_password_key', type_='unique')
        batch_op.drop_constraint('user_favoritos_fkey', type_='foreignkey')
        batch_op.drop_column('favoritos')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favoritos', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_favoritos_fkey', 'favoritos', ['favoritos'], ['id'])
        batch_op.create_unique_constraint('user_password_key', ['password'])
        batch_op.create_unique_constraint('user_name_key', ['name'])
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.alter_column('password',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_sistema_key', ['sistema'])
        batch_op.create_unique_constraint('planets_nombre_key', ['nombre'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint('people_nombre_key', ['nombre'])
        batch_op.create_unique_constraint('people_especie_key', ['especie'])

    # ### end Alembic commands ###
