"""empty message

Revision ID: 809fe3a0b360
Revises: a5cffa318ac2
Create Date: 2025-01-27 18:36:21.955368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809fe3a0b360'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('sistema', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('personaje_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('correo', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('contrasena', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('fecha_suscripcion', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('fecha_suscripcion')
        batch_op.drop_column('contrasena')
        batch_op.drop_column('correo')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    op.drop_table('favoritos')
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
