"""empty message

Revision ID: da0396bad96e
Revises: c7bfc5458a8f
Create Date: 2025-01-29 19:27:49.134976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0396bad96e'
down_revision = 'c7bfc5458a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favoritos', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favoritos', ['favoritos'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favoritos')

    # ### end Alembic commands ###
